### ISSUE TITLE
Suddenly only finding one chapter

### ISSUE THREAD

**Issue by GryphonMeidh** [Octav14n/BoFiLo#1]
I have attempted to manually update one of the stories I frequently read from sufficientvelocity.com and it failed with the message that [Filename] contains 531 chapters, more than source: 1.
The same happens when I share the url to the app. I also attempted to delete the story listing on the app then share it, but still got the same results. I tried with several different stories but all got the same results. I tried with a story from spacebattles.com and the only change was it thought the source contained 2 chapters.
Stories at questionablequesting.com work fine.

**Comment by Octav14n** [comment]
This is a upstream issue, sufficientvelocity has changed their website 
I will package a new version once the fix is available.

Bug report upstream: https://groups.google.com/forum/m/#!topic/fanfic-downloader/e0SBiO2OwwA
