### ISSUE TITLE
How to use the app? 

### ISSUE THREAD

**Issue by pcma01** [Octav14n/BoFiLo#10]
How can I use the app to download epub files?

**Comment by kifujin** [comment]
From your browser, share the URL and select Bofilo as the app to share it with. Be sure to set up the directory to store ebooks in first, write access, etc.

**Comment by pcma01** [comment]
> From your browser, share the URL and select BoFiLo as the app to share it with. Be sure to set up the directory to store ebooks in first, write access, etc.

Thanks
