### ISSUE TITLE
Bofilo closing all the time

### ISSUE THREAD

**Issue by PHBN2021** [Octav14n/BoFiLo#2]
I downloaded the app and it was functional for months but, now it closes all the time and for some motive even after I reset and clean all the data of the app, and even when I uninstall the app and download again, he returns as he previous the reset, and when I try to use he closes all the time

**Comment by Octav14n** [comment]
Do you have a crashlog by any chance?
I am looking into libraries that automatically collect all the relevant data about the crash. But I am really busy at the moment so this may take up to a week.

Which Android version are you using?

**Comment by PHBN2021** [comment]
I don't have a crash log
And my android is 12
Strangely when I use the version of the app of April 2021 it functions ok, but it doesn't download stories of fanfictio.net

**Comment by PHBN2021** [comment]
Now the previous links of stories don't appear wen reinstall the app but it continues to crash whenever I try to download a fanfic

**Comment by Octav14n** [comment]
I have uploaded a pre-release with reporting functionality, please use it to generate a error mail.

**Comment by Octav14n** [comment]
new Version is uploaded. It should fix this issue.

**Comment by PHBN2021** [comment]
It's working, thank you

Em dom., 10 de abr. de 2022 16:25, Simon K ***@***.***>
escreveu:
