### ISSUE TITLE
stuck at write file to output directory 

### ISSUE THREAD

**Issue by Grzy7316** [Octav14n/BoFiLo#7]
Device: Samsung Galaxy Tab S6 Lite
Android Version:  13
App Version: CIBuild_2023.03.04_17-38

When attempting to download a fiction from royalroad, I am able to get tto the point  where it says starting to write fole to output directory - (I have a folder called ebooks on my SD card as the output directory). The progress bar will show XX / XX chapters (all of them ) 
When I browse to my output directory, I see an epub file that exists, but it is not a valid epub file.  Is there an expected time  that it should take for the epub to be created, and if so, how long is it ?

**Comment by Octav14n** [comment]
your file should be ready in less than a second (after you see "write file to output directory"), it essetially only copies the file from the internal directory to the output directory. I have no idea what it would take to speed up this process.
